### ISSUE TITLE
Stack tecnológico, que lenguajes, frameworks, editores, DB, etc vamos a utulizar

### ISSUE THREAD

**Issue by josechavarriacr** [MercaditoProjectcr/mercaditocr#1]

**Comment by Rafa0407** [comment]
Propongo trabajar bajo el Stack MERN .... Ya para la GUI propondria, por la experiencia que tengo un poco, utilizar Meterial-UI para no dedicar muchísimo tiempo en aprender otro

**Comment by josechavarriacr** [comment]
Lo de mongo no estoy muy seguro en este momento, creo que lo mejor seria tener los datos relacionados, al ser tipo red social nos seria mas simple o la menos no logro visualizarlo con mongo. En ese caso yo propongo PERN (Postgres, Express, React, and Node)

**Comment by Rafa0407** [comment]
Perfecto, los 3 dominamos el modelo relacional bastante bien, así conceptualizamos mejor entre todos

Obtener Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by josechavarriacr** [comment]
seria super tuanis usar esto https://graphql.org/

**Comment by Rafa0407** [comment]
Ya tiene rato en el mercado, debe tener buen soporte y documentación, juega

Obtener Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by josechavarriacr** [comment]
ok, vamos cerrando este issue con el stack definido
